### ISSUE TITLE
Convert between LAMMPS and GSD format

### ISSUE THREAD

**Issue by mphoward** [mphowardlab/lammpsio#13]
Given the similarities of `lammpsio` objects to `gsd.hoomd` objects, it would be nice to have a method to convert between them. This would involve adding methods that can cast `lammpsio.Snapshot` <-> `gsd.hoomd.Snapshot`. @astatt

**Comment by astatt** [comment]
I have some python scripts to do some of it in a haphazard way. I think I/we would have to think carefully about what information should be transferred, and also what to do with cases like changing particle numbers etc... 

But I think this would be a really nice feature to have for those of us who use both lammps and hoomd in some capacity.

**Comment by mphoward** [comment]
We are doing this too, so it would definitely be helpful to have.

Also this raises a good point:

> cases like changing particle numbers etc...

Currently, the `id` is assumed to form a compact range (i.e., 1, 2, ... N). LAMMPS does not require this, and the most common case where it would be an issue is if you only write out a subset of the system rather than everything. We haven't dealt with this because we are using these mostly for initialization, or post-processing of full trajectories. Let me open an issue to fix this.

One other small thing to be careful of is that LAMMPS and HOOMD have different conventions for defining the simulation box, so there needs to be both a conversion that occurs and also a check for compatibility (all HOOMD boxes can be LAMMPS boxes, but not all LAMMPS boxes can be HOOMD boxes).
