### ISSUE TITLE
Make sure that an appropriate atom style is set when topology is present

### ISSUE THREAD

**Issue by clpetix** [mphowardlab/lammpsio#66]
We currently default the atom type to atomic but this doesn't allow bonds, etc. We should choose the atom_style to fit what has been specified in the snapshot. 

https://github.com/mphowardlab/lammpsio/blob/91aa9797afeb5a0e24feac66c27b9eabc81c22f0/src/lammpsio/data.py#L165C1-L173C37

**Comment by mphoward** [comment]
Resolved in #68
