### ISSUE TITLE
Update `copy_from` portion of `DumpFile` to work with topology

### ISSUE THREAD

**Issue by clpetix** [mphowardlab/lammpsio#69]
This should copy topology information if it is contained in the snapshot. 

https://github.com/mphowardlab/lammpsio/blob/91aa9797afeb5a0e24feac66c27b9eabc81c22f0/src/lammpsio/dump.py#L383C21-L409C70

**Comment by mphoward** [comment]
This seems like a relatively simple feature to add that someone might expect to work with topology added in. Could you take a pass at implementing it? I think you basically only need to copy the reference to the relevant topology data if it is present in `copy_from`, as a dump file will never have topology info.
